const FUNCTIONS_URL = import.meta.env.VITE_SUPABASE_URL + "/functions/v1";
const VALIDATE_MAGIC_LINK_URL = `${FUNCTIONS_URL}/validate-magic-link`;

export type MagicLinkErrorCode =
  | "token_malformed"
  | "invalid_token"
  | "link_expired"
  | "link_already_used"
  | "staff_unavailable"
  | "session_provisioning_failed"
  | "network";

export class MagicLinkError extends Error {
  code: MagicLinkErrorCode;
  constructor(code: MagicLinkErrorCode, message: string) {
    super(message);
    this.name = "MagicLinkError";
    this.code = code;
  }
}

// GENERALIZED (backend migration 20260907090000): validate-magic-link mints
// an ordinary session for whichever staff role the link's user actually
// holds — coach, owner, or front_desk — not just coaches. `purpose` says
// which landing page generated the link (session_log -> CoachQuickLog,
// add_member -> /members/add, add_pt_package -> /pt/add) so a caller that
// handles more than one purpose can branch, but it isn't itself a privilege
// boundary: the session is that user's normal role-scoped session, same RLS
// as a PIN login. See validate-magic-link/index.ts for the full reasoning.
export type RedeemedSession = {
  access_token: string;
  refresh_token: string;
  name: string;
  role: "owner" | "front_desk" | "coach";
  organization_id: string;
  location_id: string | null;
  purpose: "session_log" | "add_member" | "add_pt_package";
};

// Pre-session, same as staff-lookup-by-phone/staff-login (Login.tsx) — the
// anon key gets through the gateway, the token itself is the real
// credential. Single-use server-side (the claim happens before this ever
// returns) — this function must be called at most once per token; each
// caller (CoachQuickLog, the /members/add and /pt/add magic-link pages) is
// responsible for not retrying on a 410.
export async function redeemMagicLink(token: string): Promise<RedeemedSession> {
  let res: Response;
  try {
    res = await fetch(VALIDATE_MAGIC_LINK_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`,
      },
      body: JSON.stringify({ token }),
    });
  } catch {
    throw new MagicLinkError("network", "Couldn't reach the server — check your connection.");
  }

  const body = await res.json().catch(() => ({}));

  if (!res.ok || !body.ok) {
    const code: MagicLinkErrorCode = (
      [
        "token_malformed",
        "invalid_token",
        "link_expired",
        "link_already_used",
        "staff_unavailable",
        "session_provisioning_failed",
      ] as const
    ).includes(body.error)
      ? body.error
      : "session_provisioning_failed";

    // Deliberately doesn't name a specific WhatsApp command (the old
    // coach-only copy said "text SESSION again") — one message now covers
    // three different purposes, each generated by a different command
    // (SESSION / ADD MEMBER / ADD PT), and the error response doesn't carry
    // `purpose` (the claim can fail before a purpose is even known, e.g.
    // invalid_token). "text the bot again" is accurate for all three.
    const messages: Record<MagicLinkErrorCode, string> = {
      token_malformed: "This link isn't valid — text the bot on WhatsApp again for a new one.",
      invalid_token: "This link isn't valid — text the bot on WhatsApp again for a new one.",
      link_expired: "This link has expired — text the bot on WhatsApp again for a new one.",
      link_already_used: "This link has already been used — text the bot on WhatsApp again for a new one.",
      staff_unavailable: "You don't have access to this — ask the gym for help.",
      session_provisioning_failed: "Something went wrong on our end — text the bot on WhatsApp again to try once more.",
      network: "Couldn't reach the server — check your connection.",
    };
    throw new MagicLinkError(code, messages[code]);
  }

  return {
    access_token: body.access_token,
    refresh_token: body.refresh_token,
    name: body.name,
    role: body.role,
    organization_id: body.organization_id,
    location_id: body.location_id,
    purpose: body.purpose,
  };
}
